name: soul
description: Premium productivity and motivational app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

flutter:
  uses-material-design: false 

  assets:
    - assets/images/lockscreen_mockup.png
    - assets/images/logo.jpg
